version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  tokenizer-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tokenizer-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
